/var/log/kazoo/ecallmgr-console.log      kazoo:kazoo    640    14    *    @T00    ZN
/var/log/kazoo/ecallmgr-crash.log        kazoo:kazoo    640    14    *    @T00    ZN
/var/log/kazoo/ecallmgr-error.log        kazoo:kazoo    640    14    *    @T00    ZN
/var/log/kazoo/kazoo_apps-console.log    kazoo:kazoo    640    14    *    @T00    ZN
/var/log/kazoo/kazoo_apps-crash.log      kazoo:kazoo    640    14    *    @T00    ZN
/var/log/kazoo/kazoo_apps-error.log      kazoo:kazoo    640    14    *    @T00    ZN
