# Logging Configuration
log:
  syslog: info
  console: info
  file: error

# AMQP Configuration
amqp:
  management_url: http://guest:guest@127.0.0.1:15672
  prefetch: 50
  pool:
    size: 150
    overflow: 100
    threshold: 5
    server_confirms: false

# Datastore Configuration
data:
  config: couchdb

# CouchDB Configuration
couchdb:
  lock_system_config: false
  compact_automatically: false
  cookie: change_me
  ip: 127.0.0.1
  port: 15984
  username: kazoo
  password: change_me

# Zone Configuration
zones:
  zone1:
    local: true    # This is the local zone
    amqp:
      uri:
        - amqp://guest:guest@rabbitmq1.zone1.openkazoo.com:5672
#        - amqp://guest:guest@rabbitmq2.zone2.openkazoo.com:5672
    vms:
      - kazoo_apps:
          host: kazoo1.zone1.openkazoo.com
          cookie: change_me
      - ecallmgr:
          host: kazoo1.zone1.openkazoo.com
          cookie: change_me

#  zone2:
#    amqp:
#      uri:
#        - amqp://guest:guest@rabbitmq2.zone2.openkazoo.com:5672
#        - amqp://guest:guest@rabbitmq1.zone1.openkazoo.com:5672
#    vms:
#      - kazoo_apps:
#          host: kazoo2.zone2.openkazoo.com
#          cookie: change_me
#      - ecallmgr:
#          host: kazoo2.zone2.openkazoo.com
#          cookie: change_me
