[amqp]
uri = amqp://guest:guest@127.0.0.1:5672

[bigcouch]
compact_automatically = true
cookie = change_me
;ip = "127.0.0.1"
;port = 15984
ip = "172.16.9.15"
port = 5984
username = "admin"
password = "asdf4321"
admin_port = 15986

[kazoo_apps]
cookie = change_me

[ecallmgr]
cookie = change_me

[log]
syslog = info
console = info
file = error


